ARG BASE_IMAGE="quay.io/almalinuxorg/almalinux-bootc"
ARG BASE_VERSION="10"

FROM ${BASE_IMAGE}:${BASE_VERSION} AS base

ARG ADMIN_PASSWD
# hadolint ignore=DL4006
RUN if [ -n "${ADMIN_PASSWD}" ] ; then \
        useradd -m -d /var/home/admin -G wheel admin \
        && echo "admin:${ADMIN_PASSWD}" | chpasswd; \
    fi

# essential packages
RUN dnf install -y \
	systemd \
	git-core \
	sudo \
        dnf-plugins-core \
    && dnf install -y \
        util-linux \
        util-linux-user \
    && dnf install -y \
        epel-release \
    && dnf clean all \
    && rm -rf /var/cache/yum

# install tailscale (or use https://github.com/spotsnel/tailscale-systemd/)
RUN dnf config-manager --add-repo https://pkgs.tailscale.com/stable/rhel/10/tailscale.repo \
    && dnf install -y \
        tailscale \
    && dnf clean all \
    && rm -rf /var/cache/yum \
    && mkdir -p /var/run/tailscale /var/cache/tailscale /var/lib/tailscale

RUN systemctl enable tailscaled

# enable linger for the user (loginctl won't work without systemd running)
RUN mkdir -p /var/lib/systemd/linger \
    && touch /var/lib/systemd/linger/${USER} \
    && systemctl unmask systemd-logind

# systemd
ENTRYPOINT ["/sbin/init"]
